# TP 2 Theorie et Traitement de l'Information
## MGSI 4 - JAAFAR Leila

In [12]:
import numpy as np

## exercice 1

In [41]:
# creation des vecteurs
v1 = np.array([2,3,4])
v2 = np.array([1,0,-1])
# somme
sum_vectors = np.add(v1,v2)
# difference
subst_vectors = np.subtract(v1,v2)
# produit scalaire
prod_scalaire = np.vdot(v1, v2)
# produit vectoriel
prod_vectoriel = np.cross(v1, v2)
# print
print(f'calculs vectoriels:\n la somme: {sum_vectors}\n la difference: {subst_vectors}\n le produit scalaire: {prod_scalaire}\n le produit vectoriel: {prod_vectoriel}')

calculs vectoriels:
 la somme: [3 3 3]
 la difference: [1 3 5]
 le produit scalaire: -2
 le produit vectoriel: [-3  6 -3]


*On applique des calculs simples sur les vecteurs v1 et v2 et on print les resultats*

## exercice 2

In [77]:
v = np.array([4,-3,1])
# calcul de norme
norme_v = np.linalg.norm(v)
# normalisation du vecteur
normalisee = v / norme_v
print(f'le vecteur normalisee: {normalisee:}')

# angle entre v et u
u = np.array([1,1,0])

produit_scalaire = np.vdot(v,u)
norme_u = np.linalg.norm(u)

cos_angle = produit_scalaire / (norme_v * norme_u)
angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)

print(f'l\'angle entre v et u en radians est: {angle_rad:.3f} et en degre: {angle_deg:.3f}')

le vecteur normalisee: [ 0.78446454 -0.58834841  0.19611614]
l'angle entre v et u en radians est: 1.432 et en degre: 82.029


*On obtient le vecteur unitaire en divisant le vecteur par sa norme.*
*On suit la regle du produit scalaire: ||x||.||y||.cos(theta) afin de trouver le cos et par suite l'angle avec arccos.*

## exercice 3

In [203]:
# 1
A = np.arange(1,10).reshape(3,3)
# 2
premier = A[0,0]
# 3
derniere_col = A[:,-1]
# 4
A2 = np.multiply(A, 2)
# 5
somme_elements = np.sum(A)
# 6
B = np.ones((3,3))
# 7
addition_AB = np.add(A,B)
# 8
produit_AB = np.multiply(A,B)
# 9
transposee = np.transpose(A)
# print
print(f'''calcul matriciel:\n 1- la matrice A:\n {A} et la matrice B:\n {B}\n
2- le premiere element de la premiere ligne de A: {premier}\n
3- la derniere colonne est: {derniere_col}\n
4- on multilplie A par 2:\n {A2}\n
5- la somme de tous les elements de A: {somme_elements}\n
7- l\'addition de A et B:\n {addition_AB}\n
8- la multiplication de A et B:\n {produit_AB}\n
9- et finalement, la transposee:\n {transposee}''')

calcul matriciel:
 1- la matrice A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] et la matrice B:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

2- le premiere element de la premiere ligne de A: 1

3- la derniere colonne est: [3 6 9]

4- on multilplie A par 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

5- la somme de tous les elements de A: 45

7- l'addition de A et B:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

8- la multiplication de A et B:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

9- et finalement, la transposee:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


*Apres creation des tableaux A et B, on applique des calculs matriciaux sur eux: addition, somme, multiplication par int et des deux matrices, et calcul de transposee. Ainsi que l'acces a des elements et colonnes precises.*

## exercice 5

In [645]:
# 1
a = np.array([[1,2,1],
             [2,4,2],
             [1,2,5]])
# 2
det_a = np.linalg.det(a).astype(int)
print(f'1- le determinant de a = {det_a}')
# 3
valeurs = np.linalg.eig(a)
print(f'2- les valeurs propres: {valeurs[0]}\n les vecteurs propres:\n {valeurs[1]}')
# 5
trace_a = np.trace(a)
print(f'4- la trace de a est:{trace_a}')
# 4
# matrice diagonale
D = np.diag(valeurs[0])
# matrice des vecteurs propres
P = valeurs[1]
# matrice inverse
P1 = np.linalg.inv(P)

def diagonalisation(matrice):
    if matrice.ndim + 1 == valeurs[0].shape[0]:
        matrice_diag = P @ D @ P1
        print(f'3- la matrice; resultat de PDP^(-1) est:\n {matrice_diag}\n qui est egale a la matrice initiale et peut s\'ecrire sous la forme PDP^(-1)')
    else:
        print('On ne peut pas faire la diagonalisation!')
        
diagonalisation(a)


1- le determinant de a = 0
2- les valeurs propres: [ 7.23606798e+00 -6.10622664e-16  2.76393202e+00]
 les vecteurs propres:
 [[-3.16227766e-01 -8.94427191e-01 -3.16227766e-01]
 [-6.32455532e-01  4.47213595e-01 -6.32455532e-01]
 [-7.07106781e-01  4.13828167e-17  7.07106781e-01]]
4- la trace de a est:10
3- la matrice; resultat de PDP^(-1) est:
 [[1. 2. 1.]
 [2. 4. 2.]
 [1. 2. 5.]]
 qui est egale a la matrice initiale et peut s'ecrire sous la forme PDP^(-1)


*afin de realiser la diagonalisation d'une matrice, il faut que:<br>
1- la dimension de la matrice soit egale au nombre des valeurs propres<br>
2- si cette condition est remplie, on doit calculer:<br>
  a- la matrice diagonale (contenant les valeurs propres en diagonale.)<br>
  b- la matrice des vecteurs propres et son inverse<br>
  c- si le produit matriciel! de PDP^(-1) est egale a la matrice:<br>
donc la matrice est diagonalisable et s'ecrit sous cette forme plus simple pour des calculs futurs.*

## exercice 6

In [619]:
# 1
nombres = np.arange(5,80,5)
# 2 
max_nombres = np.max(nombres)
min_nombres = np.min(nombres)
# 3
somme = np.sum(nombres)
# il faut convertir les nombres en float
nombres = nombres.astype(float)
produit = np.prod(nombres).astype(float)
# 4
moyenne = np.mean(nombres)
medianne = np.median(nombres)
# 5
variance = np.var(nombres)
ecart_type = np.std(nombres)
# 6
etendue = np.ptp(nombres)
# 7
nombres_Q1 = np.percentile(nombres, 25)
nombres_Q2 = np.percentile(nombres, 50)
nombres_Q3 = np.percentile(nombres, 75)
# 8
nombres_90 = np.percentile(nombres, 90)
# 9
array1 = np.arange(5,55,5)
array2 = np.arange(2,22,2)
# 10
covariance = np.cov(array1, array2)[0,1]
# 11
coeff_corr = np.corrcoef(array1, array2)[0,1]
#print
dict = {
    "max": max_nombres,
    "min": min_nombres,
    "somme": somme,
    "produit": produit,
    "moyenne": moyenne,
    "medianne": medianne,
    "variance": variance,
    "ecart type": ecart_type,
    "l'etendue": etendue,
    "Q1": nombres_Q1,
    "Q2": nombres_Q2,
    "Q3": nombres_Q3,
    "90th Percentile": nombres_90,
}
dict

{'max': 75,
 'min': 5,
 'somme': 600,
 'produit': 3.9907054687499995e+22,
 'moyenne': 40.0,
 'medianne': 40.0,
 'variance': 466.6666666666667,
 'ecart type': 21.602468994692867,
 "l'etendue": 70.0,
 'Q1': 22.5,
 'Q2': 40.0,
 'Q3': 57.5,
 '90th Percentile': 68.0}

In [613]:
print(f'''pour les arrays 1: {array1} et 2: {array2}:
la covariance est egale a {covariance:.3f} et le coefficient de correlation
de Pearson est {coeff_corr:.3f}''')

pour les arrays 1: [ 5 10 15 20 25 30 35 40 45 50] et 2: [ 2  4  6  8 10 12 14 16 18 20]:
la covariance est egale a 91.667 et le coefficient de correlation
de Pearson est 1.000


*- dans cet exercice, on applique de multiples methodes en relation avec la statistique. <br> - Afin de resoudre le probleme d'avoir un produit negatif a cause de la surcharge des calculs, il faut convertir les nombres en float.
<br> - On utilise un dictionnaire pour le display pour ne pas trop charger le code avec le print.
<br> - Finalement, il faut choisir le 0,1 pour covarience et coefficient puisque ces fonctions de maniere a renvoyer une matrice 2x2*

*fin du tp 2 - theorie et traitement de l'information*